// Code generated by protoc-gen-go.
// source: testresults.proto
// DO NOT EDIT!

/*
Package owm is a generated protocol buffer package.

It is generated from these files:
	testresults.proto

It has these top-level messages:
	TestResultsProto
*/
package owm

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TestResultsProto struct {
	AgentId          *uint64 `protobuf:"varint,1,req" json:"AgentId,omitempty"`
	URI              *string `protobuf:"bytes,2,req" json:"URI,omitempty"`
	Timestamp        *string `protobuf:"bytes,3,req" json:"Timestamp,omitempty"`
	TestData         *string `protobuf:"bytes,4,req" json:"TestData,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TestResultsProto) Reset()         { *m = TestResultsProto{} }
func (m *TestResultsProto) String() string { return proto.CompactTextString(m) }
func (*TestResultsProto) ProtoMessage()    {}

func (m *TestResultsProto) GetAgentId() uint64 {
	if m != nil && m.AgentId != nil {
		return *m.AgentId
	}
	return 0
}

func (m *TestResultsProto) GetURI() string {
	if m != nil && m.URI != nil {
		return *m.URI
	}
	return ""
}

func (m *TestResultsProto) GetTimestamp() string {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return ""
}

func (m *TestResultsProto) GetTestData() string {
	if m != nil && m.TestData != nil {
		return *m.TestData
	}
	return ""
}

func init() {
}
